apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
  namespace: observability
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - name: umami
          image: ghcr.io/umami-software/umami:postgresql-latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: umami-generated-secrets
                  key: UMAMI_DATABASE_URL
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: umami-generated-secrets
                  key: UMAMI_APP_SECRET
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 3
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 3000
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
