apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: umami-secrets
  namespace: observability
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: observability-infisical-auth
        secretNamespace: observability
      secretsScope:
        envSlug: "prod"
        secretsPath: "/"
  managedSecretReference:
    secretName: umami-generated-secrets
    secretNamespace: observability
