export const DocumentType = {
    SCHOOL_CERTIFICATE: "SCHOOL_CERTIFICATE",
    ENROLLMENT_CERTIFICATE: "ENROLLMENT_CERTIFICATE",
    TRANSCRIPTS: "TRANSCRIPTS",
    OFFICIAL_DOCUMENTS_ISSUED_BY_THE_SCHOOL: "OFFICIAL_DOCUMENTS_ISSUED_BY_THE_SCHOOL",
    AGREEMENT: "AGREEMENT",
    AMENDMENTS: "AMENDMENTS",
    COMPANY_DOCUMENTS: "COMPANY_DOCUMENTS",
    OTHER: "OTHER",
} as const;

export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];
