apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: backup-s3-secrets
  namespace: postgres
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: observability-infisical-auth
        secretNamespace: observability
      secretsScope:
        envSlug: "prod"
        secretsPath: "/"
  managedSecretReference:
    secretName: backup-s3-secrets
    secretNamespace: postgres
